---
source: crates/ruff_linter/src/rules/flake8_pytest_style/mod.rs
---
PT032.py:19:5: PT032 [*] Use context-manager form of `pytest.raises()`
   |
18 | def test_error_trivial():
19 |     pytest.raises(ZeroDivisionError, func, 1, b=0)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ PT032
   |
   = help: Use `pytest.raises()` as a context-manager

ℹ Unsafe fix
16 16 | 
17 17 | 
18 18 | def test_error_trivial():
19    |-    pytest.raises(ZeroDivisionError, func, 1, b=0)
   19 |+    with pytest.raises(ZeroDivisionError):
   20 |+        func(1, b=0)
20 21 | 
21 22 | 
22 23 | def test_error_match():

PT032.py:23:5: PT032 [*] Use context-manager form of `pytest.raises()`
   |
22 | def test_error_match():
23 |     pytest.raises(ZeroDivisionError, func, 1, b=0).match("division by zero")
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ PT032
   |
   = help: Use `pytest.raises()` as a context-manager

ℹ Unsafe fix
20 20 | 
21 21 | 
22 22 | def test_error_match():
23    |-    pytest.raises(ZeroDivisionError, func, 1, b=0).match("division by zero")
   23 |+    with pytest.raises(ZeroDivisionError, match="division by zero"):
   24 |+        func(1, b=0)
24 25 | 
25 26 | 
26 27 | def test_error_assign():

PT032.py:27:15: PT032 [*] Use context-manager form of `pytest.raises()`
   |
26 | def test_error_assign():
27 |     excinfo = pytest.raises(ZeroDivisionError, func, 1, b=0)
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ PT032
   |
   = help: Use `pytest.raises()` as a context-manager

ℹ Unsafe fix
24 24 | 
25 25 | 
26 26 | def test_error_assign():
27    |-    excinfo = pytest.raises(ZeroDivisionError, func, 1, b=0)
   27 |+    with pytest.raises(ZeroDivisionError) as excinfo:
   28 |+        func(1, b=0)
28 29 | 
29 30 | 
30 31 | def test_error_kwargs():

PT032.py:31:5: PT032 [*] Use context-manager form of `pytest.raises()`
   |
30 | def test_error_kwargs():
31 |     pytest.raises(func=func, expected_exception=ZeroDivisionError)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ PT032
   |
   = help: Use `pytest.raises()` as a context-manager

ℹ Unsafe fix
28 28 | 
29 29 | 
30 30 | def test_error_kwargs():
31    |-    pytest.raises(func=func, expected_exception=ZeroDivisionError)
   31 |+    with pytest.raises(ZeroDivisionError):
   32 |+        func()
